import oracledb


def get_connection():
    
    try:
        conn = oracledb.connect(
            user="SYSTEM",
            password="Elvin123",
            dsn="localhost:1521/orcl"
        )
        return conn
    except oracledb.Error as e:
        print(f"Bağlantı xetası: {e}")
        return None


def create_table():
    
    conn = get_connection()
    if not conn:
        return

    try:
        cursor = conn.cursor()

        
        cursor.execute("""
                       CREATE TABLE isciler
                       (
                           id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           ad    VARCHAR2(50),
                           soyad VARCHAR2(50),
                           maas  NUMBER
                       )
                       """)
        conn.commit()
        print("UĞURLU: 'isciler' cədvəli yaradıldı.")

    except oracledb.DatabaseError as e:
        error_obj, = e.args
        if error_obj.code == 955:
            
            print("MƏLUMAT: Cədvəl artıq bazada var. Proqram davam edir...")
        else:
            print(f"SQL Xetası: {e}")
    finally:
        cursor.close()
        conn.close()


if __name__ == "__main__":
    create_table()